name: burger_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.0.0
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0
  dotenv: ^4.0.1
  # galileo_mysql: ^3.0.0
  mysql1: ^0.20.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.2
  http: ^0.13.0
  lints: ^2.0.0
  shelf_router_generator: ^1.0.4
  test: ^1.15.0
